config/routes.rb
Rails.application.routes.draw do
    root 'static_pages#home'
    
    resources :users
    get '/signup', to: 'users#new'
    post '/signup', to: 'users#create'
    
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    
    resources :lectures
    get '/lecture_list', to: 'lectures#lecture_list'
    post '/lecture_search', to: 'lectures#lecture_search'
    get "lecture_review/:lecture_id/:user_id", to: 'lectures#lecture_review'
    post 'lecture_review/:lecture_id/:user_id', to: 'lectures#lecture_answer'
    get 'lecture_favorite/:lecture_id/:user_id', to: 'lectures#lecture_favorite'
    get '/fav_delete/:lecture_id/:user_id', to: 'lectures#lecture_delete'
end

app/models/lecture.rb
class Lecture < ApplicationRecord
    has_many :reviews, dependent: :destroy
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
    
    before_action :logged_in_user, only: [:lecture_review, :lecture_answer, :lecture_favorite]
    before_action :correct_user,   only: [:lecture_review, :lecture_answer, :lecture_favorite]
    
    def lecture_list
        @lectures = Lecture.all
    end
    
    def show
        @lecture = Lecture.find_by(id: params[:id])
        @reviews = @lecture.reviews
        @understanding_score = understanding_calculation
        @getting_score = getting_calculation
        @interest_score = interest_calculation
        @attendance_score = attendance_calculation
        @method_score = method_calculation
        @score_score = score_calculation
        @tokutan_score = tokutan_calculation
    end
    
    def lecture_item
        @lecture = Lecture.find_by(id: params[:id])
    end
    
    def lecture_search
        @lectures = Lecture.all.order('ev_score DESC')
        if not params[:search][:search_keyword].empty?
            s_keyword = "%" + params[:search][:search_keyword] + "%"
            @lectures = Lecture.where("lec_name LIKE ?", s_keyword )
        end
        
        if not params[:search][:search_quarter].empty?
            @lectures = @lectures.where(t_quarter: params[:search][:search_quarter])
        end
        if not params[:search][:search_day].empty?
            @lectures = @lectures.where(t_day: params[:search][:search_day])
        end
        if not params[:search][:search_period].empty?
            @lectures = @lectures.where(t_period: params[:search][:search_period])
        end
        if not params[:search][:search_group].empty?
            @lectures = @lectures.where(group: params[:search][:search_group])
        end
        if not params[:search][:search_method].empty?
            @lectures = @lectures.where("ev_method LIKE ?", params[:search][:search_method])
        end
        if not params[:search][:search_major].empty?
            @lectures = @lectures.where(en_major: params[:search][:search_major])
        end
        if not params[:search][:search_attendance].empty?
            @lectures = @lectures.where(ev_attendance: params[:search][:search_attendance])
        end
        if not params[:search][:search_grade].empty?
            @lectures = @lectures.where(en_grade: params[:search][:search_grade])
        end
        if params[:search][:check_highscore] == '1'
            @lectures = @lectures.where('ev_score >= ?', 85)
        end
        if params[:search][:check_getting_easily] == '1'
            @lectures = @lectures.where('ev_getting >= ?', 85)
        end
        if params[:search][:check_understanding] == '1'
            @lectures = @lectures.where('ev_understanding >= ?', 3.5)
        end
        
        render 'lecture_list'
    end
    
    def lecture_review
        @lecture = Lecture.find_by(id: params[:lecture_id])
        @reviewer = User.find_by(id: params[:user_id])
    end
    
    def lecture_answer
        @lecture = Lecture.find_by(id: params[:lecture_id])
        @reviewer = User.find_by(id: params[:user_id])
        le_params = lecture_params
        @review = @lecture.reviews.build(user_id: @reviewer.id, 
                                understanding: le_params[:review_understanding],
                                getting: le_params[:review_getting],
                                interest: le_params[:review_interest],
                                score: le_params[:review_score],
                                tokutan: le_params[:review_tokutan],
                                attendance: le_params[:review_attendance],
                                method: le_params[:review_method],
                                comment: le_params[:review_free])
        if @review.save
            flash[:success] = 'レビューが完了しました'
            redirect_to lecture_list_path
        else
            render 'recture_review'
        end
    end
    
    def lecture_favorite
        @lecture = Lecture.find_by(id: params[:lecture_id])
        @user = User.find_by(id: params[:user_id])
        @favorite_lecture = @user.favorites.build(user_id: @user.id,
                                                  lec_id: @lecture.id,
                                                  fav_day: @lecture.t_day,
                                                  fav_period: @lecture.t_period)
        if @favorite_lecture.save
            flash[:success] = "#{@lecture.lec_name}がMy時間割に追加されました。"
            redirect_to "/lectures/#{@lecture.id}"
        else
            render 'lectures/show'
        end
    end
    
    def lecture_delete
        user = User.find_by(id: params[:user_id])
        favorite = user.favorites.find_by(lec_id: params[:lecture_id])
        favorite.destroy
        redirect_to user
    end
    
    
    private
        
        def logged_in_user
            unless logged_in?
                store_location
                flash[:danger] = 'ログインが必要です。'
                redirect_to login_url
            end
        end
        
        def understanding_calculation
            the_lecture = Lecture.find_by(id: params[:id])
            reviews = the_lecture.reviews
            if reviews.count == 0
                score = 3.0
            else
                understanding_score = 0
                for review in reviews do
                    understanding_score = understanding_score + review.understanding
                end
                score = BigDecimal((understanding_score.to_f / reviews.count.to_f).to_s).floor(1).to_f
                return score
            end
        end
        
        def getting_calculation
            the_lecture = Lecture.find_by(id: params[:id])
            reviews = the_lecture.reviews
            if reviews.count == 0
                score = 3.0
            else
                getting_score = 0
                for review in reviews do
                    getting_score = getting_score + review.getting
                end
                score = BigDecimal((getting_score.to_f / reviews.count.to_f).to_s).floor(1).to_f
                return score
            end
        end
        
        def interest_calculation
            the_lecture = Lecture.find_by(id: params[:id])
            reviews = the_lecture.reviews
            if reviews.count == 0
                score = 3.0
            else
                interest_score = 0
                for review in reviews do
                    interest_score = interest_score + review.interest
                end
                score = BigDecimal((interest_score.to_f / reviews.count.to_f).to_s).floor(1).to_f
                return score
            end
        end
        
        def attendance_calculation
            the_lecture = Lecture.find_by(id: params[:id])
            reviews = the_lecture.reviews
            at = reviews.where(attendance: '毎回出席有').count
            at_un = reviews.where(attendance: 'ときどき出席有').count
            un = reviews.where(attendance: '出席無し').count
            max = [at, at_un, un].max
            if max == at
                score = '毎回出席有'
            elsif max == at_un
                score = 'ときどき出席有'
            else
                score = '出席無し'
            end
            return score
        end
        
        def method_calculation
            the_lecture = Lecture.find_by(id: params[:id])
            reviews = the_lecture.reviews
            at = reviews.where(attendance: 'テスト100%').count
            at_un = reviews.where(attendance: 'テストと課題').count
            un = reviews.where(attendance: '課題100%').count
            max = [at, at_un, un].max
            if max == at
                score = 'テスト100%'
            elsif max == at_un
                score = 'テストと課題'
            else
                score = '課題100%'
            end
            return score
        end
        
        def score_calculation
            the_lecture = Lecture.find_by(id: params[:id])
            reviews = the_lecture.reviews
            if reviews.count == 0
                score = 80
            else
                score_score = 0
                for review in reviews do
                    score_score = score_score + review.score
                end
                score = BigDecimal((score_score.to_f / reviews.count.to_f).to_s).floor(1).to_f
                return score
            end
        end
        
        def tokutan_calculation
            the_lecture = Lecture.find_by(id: params[:id])
            reviews = the_lecture.reviews
            if reviews.count == 0
                score = 80
            else
                at = reviews.where(tokutan: '得単').count.to_f
                un = reviews.where(tokutan: '落単').count.to_f
                score = BigDecimal((at.to_f / (at.to_f+un.to_f)).to_s).floor(1).to_f*100
            end
            return score
        end

        def lecture_params
           params.require(:review).permit(:review_understanding, 
                                          :review_attendance,
                                          :review_getting,
                                          :review_interest,
                                          :review_free,
                                          :review_score,
                                          :review_tokutan,
                                          :review_free)
        end
        
        def correct_user
            @user = User.find_by(id: params[:user_id])
            redirect_to root_url unless current_user?(@user)
        end
    end

app/helpers/lectures_helper.rb
module LecturesHelper
    
    def total_evaluation(lecture)
        understanding_sum = 3
        getting_sum = 3
        interest_sum = 3
        score_sum = 3
        reviews = lecture.reviews
        for review in reviews do
            understanding_sum = understanding_sum + review.understanding
            getting_sum  = getting_sum + review.getting
            interest_sum = interest_sum + review.interest
            score_sum = score_sum + ((review.score-50)/10)
        end
        total_score = (understanding_sum + getting_sum + interest_sum + score_sum) / (4 * (reviews.count + 1))
        ret_score = BigDecimal(total_score.to_s).floor(1).to_f
        return ret_score
    end
    
end

app/views/lectures/lecture_list.html.erb
<div class='lectures-wrapper clearfix'>
    <div class='search-forms'>
        <%= form_for(:search, url: lecture_search_path) do |f| %>
            <div class='keyword-search'>
                <p>講義名で検索する</p>
                <%= f.text_field :search_keyword, class: 'form-control-2' %>
                <%= f.submit '講義検索', class: 'btn search-btn' %>
            </div>
            <ul class='search-items'>
                <li class='search-item'>
                    <p>該当学期</p>
                    <%= f.select :search_quarter,
                    [['1Q', 1], ['2Q', 2], ['3Q', 3], ['4Q', 4]] ,:include_blank => true,  class: 'form-control-3' %>
                </li>
                <li class='search-item'>
                    <p>曜日</p>
                    <%= f.select :search_day, 
                    [['月曜日', '月曜日'], ['火曜日', '火曜日'], ['水曜日', '水曜日'],
                    ['木曜日', '木曜日'], ['金曜日', '金曜日']] ,:include_blank => true, class: 'form-control-3' %>
                </li>
                <li class='search-item'>
                    <p>開始時限</p>
                    <%= f.select :search_period, 
                    [['1限', 1], ['2限', 2], ['3限', 3], ['4限', 4], ['5限', 5]] ,:include_blank => true, class: 'form-control-3' %>
                </li>
                <li class='search-item'>
                    <p>科目群</p>
                    <%= f.select :search_group, [['理工系教養科目群', '理工系教養科目群'], ['文系教養科目群', '文系教養科目群'], ['専門科目群', '専門科目群'], ['選択科目群', '選択科目群']], :include_blank => true, class: 'form-control-3' %>
                </li>
                <li class='search-item'>
                    <p>推奨系</p>
                    <%= f.select :search_major, 
                    [['数学系', '数学系'], ['物理学系', '物理学系'], ['化学系', '化学系'], ['地球惑星科学系', '地球惑星科学系'], 
                    ['機械系', '機械系'], ['システム制御系', 'システム制御系'], ['電気電子系', '電気電子系'], ['情報通信系', '情報通信系'], ['経営工学系', '経営工学系'], 
                    ['材料系', '材料系'], ['応用化学系', '応用化学系'], 
                    ['数理計算科学系', '数理計算科学系'], ['情報工学系', '情報工学系'],
                    ['生命理工学系', '生命理工学系'], ['数学系', '数学系'], 
                    ['建築学系', '建築学系'], ['土木・環境工学系', '土木・環境工学系'], ['融合理工学系', '融合理工学系']],:include_blank => true, class: 'form-control-3' %>
                </li>
                <li class='search-item'>
                    <p>推奨学年</p>
                    <%= f.select :search_grade, [['B1', 1], ['B2', 2], ['B3', 3]], :include_blank => true, class: 'form-control-3' %>
                </li>
                <li class='search-item'>
                    <p>評価方法</p>
                    <%= f.select :search_method, [['テスト100%', '期末100%'], ['レポートとテスト', '期末70% 出席30%'], ['レポート100%', 'レポート100%']], :include_blank => true, class: 'form-control-3' %>
                </li>
                <li class='search-item'>
                    <p>出席</p>
                    <%= f.select :search_attendance, [['毎回有', '毎回有'], ['時々有', '時々有'], ['無し', '無']], :include_blank => true, class: 'form-control-3' %>
                </li>
                <br>
                <li class='search-item check'>
                    <p>高得点が取れる</p>
                    <%= f.check_box :check_highscore, class: 'check-box' %>
                </li>
                <li class='search-item check'>
                    <p>単位が取りやすい</p>
                    <%= f.check_box :check_getting_easily, class: 'check-box' %>
                </li>
                <li class='search-item check'>
                    <p>単位取得率が高い</p>
                    <%= f.check_box :check_getting_easily2, class: 'check-box' %>
                </li>
                <li class='search-item check'>
                    <p>理解度が高い</p>
                    <%= f.check_box :check_understanding, class: 'check-box' %>
                </li>
            </ul>
        <% end %>
    </div>
    
    <div class='search-information'>
        <p class='result'>検索結果; <%= @lectures.count %>件</p>
        <p class='hit-number'>1-20件の検索結果を表示</p>
    </div>
    
    <div class='search-order'>
        <p>表示順;</p>
        <ul class='condition-items'>
            <li class='condition-item active'><a href='#'>おすすめ</a></li>
            <li class='condition-item'><a href='#'>単位取得率</a></li>
            <li class='condition-item'><a href='#'>平均点</a></li>
            <li class='condition-item'><a href='#'>理解度</a></li>
            <li class='condition-item'><a href='#'>面白さ</a></li>
        </ul>
    </div>
    
    <div class='lecture-items'>
        <% @lectures.each do |lecture| %>
            <a class='lecture-item', href= 'lectures/<%=lecture.id%>'>
                <div class='lec-information-left'>
                    <p class='lec-title'><%= lecture.lec_name %></p>
                    <p class='total-evaluation'>総合評価　<%= total_evaluation(lecture) %></p>
                </div>
                <div class='lec-information-center'>
                    <p class='attendance'>出席　<%= lecture.ev_attendance %></p>
                    <p class='method'>評価　<%= lecture.ev_method %></p>
                </div>
                <div class='lec-information-right'>
                    <p class='major'><%= lecture.en_major %></p>
                    <p class='professor'>担当教授　<%= lecture.professor %></p>
                    <p class='date'>
                        <%= lecture.t_quarter %>Q <%= lecture.t_day %> <%= lecture.t_period %>時限</p>
                </div>
            </a>
        <% end %>
    </div>
    <div class='lecture-items responsive'>
        <% @lectures.each do |lecture| %>
            <a class='lecture-item', href= 'lectures/<%=lecture.id%>'>
                <div class='lec-information-left'>
                    <p class='lec-title'><%= lecture.lec_name %></p>
                    <p class='total-evaluation'>総合評価　<%= total_evaluation(lecture) %></p>
                </div>
                <div class='lec-information-right'>
                    <p class='major'><%= lecture.en_major %></p>
                    <p class='professor'>担当教授　<%= lecture.professor %></p>
                    <p class='date'>
                        <%= lecture.t_quarter %>Q <%= lecture.t_day %> <%= lecture.t_period %>時限</p>
                </div>
                <div class='lec-information-center'>
                    <p class='attendance'>出席<br><%= lecture.ev_attendance %></p>
                    <span class='dotted-line'></span>
                    <p class='method'>評価<br><%= lecture.ev_method %></p>
                </div>
            </a>
        <% end %>
    </div>
</div>

app/views/lectures/lecture_review.html.erb
<div class='lecture_review_wrapper'>
    <h3 class='title'>授業レビュー回答 (1分)</h3>
    <%= form_for(:review, url: "/lecture_review/#{@lecture.id}/#{@reviewer.id}_path") do |f| %>
        <p class='lecture_name'><%= @lecture.lec_name %></p>
        <p class='warning'>※必須</p>
        <ul class='question-items'>
            <li class='question-item'>
                <p class='content'>Q1<br>授業内容の理解度を5段階で教えてください。</p>
                <%= f.radio_button :review_understanding, 1, id: 'us-1' %>
                <%= f.label :'1', class: 'radio-label', for: 'us-1' %>
                <%= f.radio_button :review_understanding, 2, id: 'us-2' %>
                <%= f.label :'2', class: 'radio-label', for: 'us-2' %>
                <%= f.radio_button :review_understanding, 3, id: 'us-3' %>
                <%= f.label :'3', class: 'radio-label', for: 'us-3' %>
                <%= f.radio_button :review_understanding, 4, id: 'us-4' %>
                <%= f.label :'4', class: 'radio-label', for: 'us-4' %>
                <%= f.radio_button :review_understanding, 5, id: 'us-5' %>
                <%= f.label :'5', class: 'radio-label', for: 'us-5' %>
            </li>
            <li class='question-item'>
                <p class='content'>Q2<br>授業内容の単位取得難易度を5段階で教えてください。</p>
                <%= f.radio_button :review_getting, 1, id: 'get-1' %>
                <%= f.label :'1', class: 'radio-label', for: 'get-1' %>
                <%= f.radio_button :review_getting, 2, id: 'get-2' %>
                <%= f.label :'2', class: 'radio-label', for: 'get-2' %>
                <%= f.radio_button :review_getting, 3, id: 'get-3' %>
                <%= f.label :'3', class: 'radio-label', for: 'get-3' %>
                <%= f.radio_button :review_getting, 4, id: 'get-4' %>
                <%= f.label :'4', class: 'radio-label', for: 'get-4' %>
                <%= f.radio_button :review_getting, 5, id: 'get-5' %>
                <%= f.label :'5', class: 'radio-label', for: 'get-5' %>
            </li>
            <li class='question-item'>
                <p class='content'>Q3<br>授業内容の面白さを5段階で教えてください。</p>
                <%= f.radio_button :review_interest, 1, id: 'int-1' %>
                <%= f.label :'1', class: 'radio-label', for: 'int-1' %>
                <%= f.radio_button :review_interest, 2, id: 'int-2' %>
                <%= f.label :'2', class: 'radio-label', for: 'int-2' %>
                <%= f.radio_button :review_interest, 3, id: 'int-3' %>
                <%= f.label :'3', class: 'radio-label', for: 'int-3' %>
                <%= f.radio_button :review_interest, 4, id: 'int-4' %>
                <%= f.label :'4', class: 'radio-label', for: 'int-4' %>
                <%= f.radio_button :review_interest, 5, id: 'int-5' %>
                <%= f.label :'5', class: 'radio-label', for: 'int-5' %>
            </li>
            <li class='question-item question-item-square'>
                <p class='content'>Q4<br>取得点数を教えてください</p>
                <%= f.radio_button :review_score, 55, id: 'sco-1' %>
                <%= f.label :'60~', class: 'radio-label radio-label-first', for: 'sco-1' %>
                <%= f.radio_button :review_score, 65, id: 'sco-2' %>
                <%= f.label :'60~70', class: 'radio-label', for: 'sco-2' %>
                <%= f.radio_button :review_score, 75, id: 'sco-3' %>
                <%= f.label :'70~80', class: 'radio-label', for: 'sco-3' %>
                <%= f.radio_button :review_score, 85, id: 'sco-4' %>
                <%= f.label :'80~90', class: 'radio-label', for: 'sco-4' %>
                <%= f.radio_button :review_score, 95, id: 'sco-5' %>
                <%= f.label :'90~100', class: 'radio-label', for: 'sco-5' %>
            </li>
            <li class='question-item question-item-square'>
                <p class='content'>Q5<br>単位の取得状況を教えてください.</p>
                <%= f.radio_button :review_tokutan, '得単', id: 'tok-1' %>
                <%= f.label :'得単', class: 'radio-label radio-label-first', for: 'tok-1' %>
                <%= f.radio_button :review_tokutan, '落単', id: 'tok-2' %>
                <%= f.label :'落単', class: 'radio-label', for: 'tok-2' %>
            </li>
            <li class='question-item question-item-square wide'>
                <p class='content'>Q6<br>出席義務について教えてください。</p>
                <%= f.radio_button :review_attendance, '毎回出席有', id: 'att-1' %>
                <%= f.label :'毎回出席有', class: 'radio-label radio-label-first', for: 'att-1' %>
                <%= f.radio_button :review_attendance, 'ときどき出席有', id: 'att-2' %>
                <%= f.label :'ときどき出席有', class: 'radio-label', for: 'att-2' %>
                <%= f.radio_button :review_attendance, '出席無し', id: 'att-3' %>
                <%= f.label :'出席無し', class: 'radio-label', for: 'att-3' %>
            </li>
            <li class='question-item question-item-square wide'>
                <p class='content'>Q7<br>成績評価の方法を教えてください。</p>
                <%= f.radio_button :review_method, 'テスト100%', id: 'met-1' %>
                <%= f.label :'テスト100%', class: 'radio-label radio-label-first', for: 'met-1' %>
                <%= f.radio_button :review_method, 'テストと課題', id: 'met-2' %>
                <%= f.label :'テストと課題', class: 'radio-label', for: 'met-2' %>
                <%= f.radio_button :review_method, '課題100%', id: 'met-3' %>
                <%= f.label :'課題100%', class: 'radio-label', for: 'met-3' %>
                <%= f.radio_button :review_method, 'その他', id: 'met-4' %>
                <%= f.label :'その他', class: 'radio-label', for: 'met-4' %>
            </li>
            <li class='question-item'>
                <p class='content'>Q8<br>その他、自由な印象を教えてください。</p>
                <%= f.text_area :review_free, class: 'comment-form' %>
            </li>
        </ul>
        <%= f.submit '授業評価を送信', class: 'form-btn' %>
    <% end %>
</div>

app/views/lectures/show.html.erb
<div class='lecture-wrapper'>
    <div class='top-information'>
        <div class='left'>
            <p class='name'><%= @lecture.lec_name %></p>
            <p class='total-evaluation'>総合評価　<%= total_evaluation(@lecture) %></p>
        </div>
        <div class='right'>
            <% if logged_in? %>
                <a class='review-button favorite' href="/lecture_favorite/<%= @lecture.id %>/<%= current_user.id %>">My時間割に追加</a>
                <a class='review-button' href="/lecture_review/<%= @lecture.id %>/<%= current_user.id %>">評価を回答する</a>
            <% end %>
            <p class='major'><%= @lecture.en_major %> <%= @lecture.en_grade %>00</p>
            <p class='professor'>担当; <%= @lecture.professor %></p>
            <p class='date'><%= @lecture.t_quarter %>Q<%= @lecture.t_day %><%= @lecture.t_period %>時限</p>
        </div>
    </div>
    <p class='border'> </p>
    <div class='middle-information'>
        <div class='left'>
            <p><span class='question'>授業内容理解度</span><span class='answer'><%= @understanding_score %></span></p>
            <p><span class='question'>単位取得難易度</span><span class='answer'><%= @getting_score %></span></p>
            <p><span class='question'>授業の面白さ</span><span class='answer'><%= @interest_score %></span></p>
            <p><span class='question'>出席義務</span><span class='answer'><%= @attendance_score %></span></p>
            <p><span class='question'>成績評価</span><span class='answer'><%= @method_score %></span></p>
        </div>
        <div class='right'>
            <p><span class='question'>平均点数</span><span class='answer'><%= @score_score %></span></p>
            <p><span class='question'>単位取得率</span><span class='answer'><%= @tokutan_score %>%</span></p>
            <p><span class='question'>掲載予定</span><span class='answer'><%= @lecture.ev_score %></span></p>
        </div>
    </div>
    <p class='border'> </p>
    <div class='bottom-information'>
        <p class='review-title'>授業レビュー</p>
        <% if logged_in? %>
            <a class='review-button' href="/lecture_review/<%= @lecture.id %>/<%= current_user.id %>">評価を回答する</a>
        <% end %>
        <ul class='review-items'>
            <% require 'date' %>
            <% for review in @reviews %>
            <% reviewer = User.find_by(id: review.user_id) %>
                <% if not review.comment.empty? %>
                    <li class='review-item'>
                        <p class='reviewer'>
                            <%= reviewer.major %>系 <%= reviewer.grade %>年
                            <span><%= review.created_at.strftime("%Y年%m月%d日") %>に回答</span>
                        </p>
                        <p class='comment'>
                            <%= review.comment %>
                        </p>
                    </li>
                <% end %>
            <% end %>
        </ul>
    </div>
</div>