config/routes.rb
Rails.application.routes.draw do
    root 'static_pages#home'
    
    resources :users
    get '/signup', to: 'users#new'
    post '/signup', to: 'users#create'
    
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    
    resources :lectures
    get '/lecture_list', to: 'lectures#lecture_list'
    post '/lecture_search', to: 'lectures#lecture_search'
    get "lecture_review/:lecture_id/:user_id", to: 'lectures#lecture_review'
    post 'lecture_review/:lecture_id/:user_id', to: 'lectures#lecture_answer'
    get 'lecture_favorite/:lecture_id/:user_id', to: 'lectures#lecture_favorite'
    get '/fav_delete/:lecture_id/:user_id', to: 'lectures#lecture_delete'
end

app/views/layouts/_footer.html.erb
<footer class='footer clearfix'>
    <div class='footer-items'>
        <ul>
            <a href='#' class='footer-item'><li>利用規約</li></a>
            <a href='#' class='footer-item'><li>プライバシーポリシー</li></a>
            <a href='#' class='footer-item'><li>お問い合わせ</li></a>
        </ul>
    </div>
    <p>@copyright Lecceed</p>
</footer>

app/views/layouts/_header.html.erb
<header class='header clearfix'>
    <h1 class='header-left'><a href='/'>Lecceed</a></h1>
        <% if logged_in? %>
            <div class='header-right'>
            <%= link_to 'My時間割', user_path(current_user), class: 'log-btn' %>
            <%= link_to 'ログアウト', logout_path, class: 'log-btn', method: :delete %>
            <%= link_to '講義を探す', lecture_list_path, class: 'find-btn' %>
            </div>
            <div class='ladder-button'>
                <i class='fa fa-list'></i>
                <i class="fa fa-times delete"></i>
                <div class='ladder-menu'>
                    <%= link_to '講義を探す', lecture_list_path, class: 'menu' %>
                    <%= link_to 'My時間割', user_path(current_user), class: 'menu' %>
                    <%= link_to 'ログアウト', logout_path, class: 'menu', method: :delete %>
                    <%= link_to 'プロフィール編集', edit_user_path(current_user), class: 'menu' %>
                </div>
            </div>
        <% else %>
            <div class='header-right narrow'>
            <%= link_to '新規登録', signup_path, class: 'log-btn' %>
            <%= link_to 'ログイン', login_path, class: 'log-btn' %>
            <%= link_to '講義を探す', lecture_list_path, class: 'find-btn' %>
            </div>
            <div class='ladder-button'>
                <i class='fa fa-list'></i>
                <i class="fa fa-times delete"></i>
                <div class='ladder-menu'>
                    <a class='menu' href='/login'>ログイン</a>
                    <a class='menu' href='/signup'>新規登録</a>
                    <a class='menu' href='/lecture_list'>講義を探す</a>
                </div>
            </div>
        <% end %>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="..../assets/stylesheet/fontawesome-free" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>